export const exerciseSuggestionsModels = [
  {
    id: "EX001",
    name: "Chạy bộ",
    goal: "Cải thiện sức bền",
    muscleGroup: "Chân, Tim mạch",
    duration: 30,
    instructions: "Chạy bộ với tốc độ ổn định trong 30 phút. Đảm bảo tư thế đúng, không đổ người quá nhiều.",
  },
  {
    id: "EX002",
    name: "Hít đất",
    goal: "Tăng sức mạnh cơ ngực",
    muscleGroup: "Ngực, Tay sau",
    duration: 10,
    instructions: "Thực hiện hít đất 3 hiệp, mỗi hiệp 15 lần. Giữ lưng thẳng, hạ ngực xuống sát đất.",
  },
  {
    id: "EX003",
    name: "Plank",
    goal: "Tăng sức mạnh core",
    muscleGroup: "Cơ bụng",
    duration: 5,
    instructions: "Giữ tư thế plank trong 3 hiệp, mỗi hiệp 60 giây. Không để hông bị võng hoặc nhô cao.",
  },
  {
    id: "EX004",
    name: "Squat",
    goal: "Tăng sức mạnh chân",
    muscleGroup: "Chân, Mông",
    duration: 15,
    instructions: "Thực hiện squat 4 hiệp, mỗi hiệp 12 lần. Hạ người xuống sao cho đùi song song mặt đất.",
  },
  {
    id: "EX005",
    name: "Đạp xe",
    goal: "Cải thiện sức bền và đốt calo",
    muscleGroup: "Chân, Tim mạch",
    duration: 40,
    instructions: "Đạp xe với tốc độ trung bình trong 40 phút, giữ nhịp thở đều đặn.",
  },
  {
    id: "EX006",
    name: "Chống đẩy tay sau",
    goal: "Tăng sức mạnh tay",
    muscleGroup: "Tay sau",
    duration: 10,
    instructions: "Thực hiện 3 hiệp, mỗi hiệp 12 lần. Sử dụng ghế làm điểm tựa để chống đẩy.",
  },
  {
    id: "EX007",
    name: "Tập yoga",
    goal: "Giảm căng thẳng",
    muscleGroup: "Toàn thân",
    duration: 20,
    instructions: "Thực hiện chuỗi yoga cơ bản như tư thế cây cầu, chiến binh. Giữ mỗi tư thế 30 giây.",
  },
  {
    id: "EX008",
    name: "Burpees",
    goal: "Đốt calo nhanh",
    muscleGroup: "Toàn thân",
    duration: 5,
    instructions: "Thực hiện 2 hiệp, mỗi hiệp 10 lần. Nhảy lên, chống đẩy và đứng dậy liên tục.",
  },
  {
    id: "EX009",
    name: "Deadlift",
    goal: "Tăng sức mạnh toàn thân",
    muscleGroup: "Chân, Lưng dưới",
    duration: 15,
    instructions: "Thực hiện 4 hiệp, mỗi hiệp 8 lần. Dùng tạ phù hợp, giữ lưng thẳng trong suốt bài tập.",
  },
  {
    id: "EX010",
    name: "Nhảy dây",
    goal: "Tăng nhịp tim",
    muscleGroup: "Chân, Tim mạch",
    duration: 10,
    instructions: "Nhảy dây liên tục trong 3 hiệp, mỗi hiệp 2 phút. Giữ nhịp thở đều đặn.",
  },
  {
    id: "EX011",
    name: "Lunges",
    goal: "Tăng sức mạnh và linh hoạt chân",
    muscleGroup: "Chân, Mông",
    duration: 10,
    instructions: "Thực hiện 3 hiệp, mỗi hiệp 12 bước mỗi bên. Giữ lưng thẳng, đầu gối không vượt quá ngón chân.",
  },
  {
    id: "EX012",
    name: "Kéo xà",
    goal: "Tăng sức mạnh cơ lưng",
    muscleGroup: "Lưng, Tay trước",
    duration: 8,
    instructions: "Thực hiện 3 hiệp, mỗi hiệp 8-10 lần. Đảm bảo không vung người khi kéo xà.",
  },
  {
    id: "EX013",
    name: "Bài tập cầu mông",
    goal: "Cải thiện cơ mông",
    muscleGroup: "Mông, Lưng dưới",
    duration: 5,
    instructions: "Thực hiện 3 hiệp, mỗi hiệp 15 lần. Nâng hông lên cao và giữ trong 2 giây.",
  },
  {
    id: "EX014",
    name: "Đứng tấn",
    goal: "Tăng sức bền chân",
    muscleGroup: "Chân",
    duration: 5,
    instructions: "Giữ tư thế đứng tấn trong 3 hiệp, mỗi hiệp 60 giây.",
  },
  {
    id: "EX015",
    name: "Bài tập cầu vai",
    goal: "Phát triển cơ vai",
    muscleGroup: "Vai, Cổ",
    duration: 10,
    instructions: "Thực hiện nâng tạ tay hoặc thanh tạ trong 3 hiệp, mỗi hiệp 12 lần.",
  },
  {
    id: "EX016",
    name: "Bơi lội",
    goal: "Tăng sức bền toàn thân",
    muscleGroup: "Toàn thân",
    duration: 30,
    instructions: "Bơi tự do trong 30 phút. Duy trì nhịp thở đều và chuyển động nhịp nhàng.",
  },
  {
    id: "EX017",
    name: "Leo cầu thang",
    goal: "Đốt calo",
    muscleGroup: "Chân, Tim mạch",
    duration: 15,
    instructions: "Leo cầu thang liên tục trong 3 hiệp, mỗi hiệp 5 phút. Giữ tư thế thẳng.",
  },
  {
    id: "EX018",
    name: "Gập bụng",
    goal: "Phát triển cơ bụng",
    muscleGroup: "Cơ bụng",
    duration: 10,
    instructions: "Thực hiện 3 hiệp, mỗi hiệp 15 lần. Giữ lưng không nâng cao khỏi mặt đất.",
  },
  {
    id: "EX019",
    name: "Kéo dây kháng lực",
    goal: "Tăng sức mạnh cơ tay",
    muscleGroup: "Tay, Vai",
    duration: 8,
    instructions: "Thực hiện kéo dây kháng lực trong 3 hiệp, mỗi hiệp 12 lần.",
  },
  {
    id: "EX020",
    name: "Hít thở sâu",
    goal: "Thư giãn",
    muscleGroup: "Toàn thân",
    duration: 5,
    instructions: "Ngồi ở tư thế thoải mái, hít thở sâu trong 5 phút để giảm căng thẳng.",
  },
];
