export const mealSuggestionsModels = [
  {
    id: "MEAL001",
    name: "Salad rau củ",
    calories: 50,
    proteins: 1.2,
    fats: 0.3,
    carbs: 10,
    ingredients: "Rau xà lách, cà rốt, cà chua, dầu ô liu",
    instructions: "Trộn các nguyên liệu với dầu ô liu, thêm muối và tiêu.",
  },
  {
    id: "MEAL002",
    name: "Cơm gà xối mỡ",
    calories: 230,
    proteins: 15,
    fats: 10,
    carbs: 25,
    ingredients: "Gạo, thịt gà, dầu ăn, gia vị",
    instructions: "Chiên gà, nấu cơm và dọn ra đĩa với rau sống.",
  },
  {
    id: "MEAL003",
    name: "Phở bò",
    calories: 180,
    proteins: 12,
    fats: 5,
    carbs: 20,
    ingredients: "Bánh phở, thịt bò, hành lá, nước dùng",
    instructions: "Nấu nước dùng, chần bánh phở và thịt bò, thêm rau thơm.",
  },
  {
    id: "MEAL004",
    name: "Bánh mì ốp la",
    calories: 250,
    proteins: 9,
    fats: 8,
    carbs: 30,
    ingredients: "Bánh mì, trứng gà, bơ",
    instructions: "Chiên trứng với bơ, dùng kèm bánh mì.",
  },
  {
    id: "MEAL005",
    name: "Bún chả",
    calories: 300,
    proteins: 14,
    fats: 10,
    carbs: 35,
    ingredients: "Bún, thịt heo nướng, nước mắm chua ngọt, rau sống",
    instructions: "Nướng thịt, dọn bún và rau, ăn cùng nước mắm.",
  },
  {
    id: "MEAL006",
    name: "Cháo gà",
    calories: 110,
    proteins: 8,
    fats: 2,
    carbs: 15,
    ingredients: "Gạo, thịt gà, hành, tiêu",
    instructions: "Nấu cháo từ gạo, thêm thịt gà xé và hành lá.",
  },
  {
    id: "MEAL007",
    name: "Canh chua cá lóc",
    calories: 70,
    proteins: 10,
    fats: 2,
    carbs: 5,
    ingredients: "Cá lóc, cà chua, me, rau thơm",
    instructions: "Nấu cá với nước me, thêm rau và cà chua.",
  },
  {
    id: "MEAL008",
    name: "Gỏi cuốn",
    calories: 80,
    proteins: 5,
    fats: 1,
    carbs: 12,
    ingredients: "Bánh tráng, tôm, thịt heo, rau sống",
    instructions: "Cuốn các nguyên liệu với bánh tráng, chấm mắm nêm.",
  },
  {
    id: "MEAL009",
    name: "Bò bít tết",
    calories: 250,
    proteins: 20,
    fats: 12,
    carbs: 5,
    ingredients: "Thịt bò, bơ, tiêu, khoai tây",
    instructions: "Chiên thịt bò với bơ, ăn kèm khoai tây chiên.",
  },
  {
    id: "MEAL010",
    name: "Trứng hấp",
    calories: 70,
    proteins: 6,
    fats: 5,
    carbs: 1,
    ingredients: "Trứng gà, nước, hành",
    instructions: "Đánh trứng với nước, hấp chín, thêm hành.",
  },
  {
    id: "MEAL011",
    name: "Mì Ý sốt bò bằm",
    calories: 210,
    proteins: 10,
    fats: 8,
    carbs: 25,
    ingredients: "Mì Ý, thịt bò bằm, sốt cà chua",
    instructions: "Luộc mì, nấu sốt, trộn đều và dọn ra đĩa.",
  },
  {
    id: "MEAL012",
    name: "Súp cua",
    calories: 90,
    proteins: 7,
    fats: 2,
    carbs: 10,
    ingredients: "Thịt cua, bắp, trứng gà, bột năng",
    instructions: "Nấu súp từ nguyên liệu, khuấy đều đến khi sệt.",
  },
  {
    id: "MEAL013",
    name: "Cá kho tộ",
    calories: 200,
    proteins: 18,
    fats: 10,
    carbs: 5,
    ingredients: "Cá, nước mắm, đường, tiêu",
    instructions: "Kho cá với nước mắm và gia vị, ăn với cơm.",
  },
  {
    id: "MEAL014",
    name: "Tôm chiên xù",
    calories: 150,
    proteins: 12,
    fats: 6,
    carbs: 10,
    ingredients: "Tôm, bột chiên xù, trứng gà",
    instructions: "Nhúng tôm vào bột và trứng, chiên vàng giòn.",
  },
  {
    id: "MEAL015",
    name: "Đậu hũ sốt cà chua",
    calories: 90,
    proteins: 5,
    fats: 2,
    carbs: 10,
    ingredients: "Đậu hũ, cà chua, hành",
    instructions: "Chiên đậu, nấu sốt cà, cho đậu vào đảo đều.",
  },
  {
    id: "MEAL016",
    name: "Thịt kho trứng",
    calories: 250,
    proteins: 15,
    fats: 15,
    carbs: 5,
    ingredients: "Thịt ba chỉ, trứng gà, nước mắm, đường",
    instructions: "Kho thịt và trứng với nước mắm, ăn với cơm.",
  },
  {
    id: "MEAL017",
    name: "Mì gói xào trứng",
    calories: 300,
    proteins: 10,
    fats: 12,
    carbs: 40,
    ingredients: "Mì gói, trứng gà, rau cải",
    instructions: "Luộc mì, xào cùng trứng và rau.",
  },
  {
    id: "MEAL018",
    name: "Bánh xèo",
    calories: 180,
    proteins: 8,
    fats: 6,
    carbs: 25,
    ingredients: "Bột bánh xèo, thịt heo, tôm, giá đỗ",
    instructions: "Đổ bột, cho nhân vào và chiên vàng.",
  },
  {
    id: "MEAL019",
    name: "Lẩu thái",
    calories: 150,
    proteins: 10,
    fats: 5,
    carbs: 15,
    ingredients: "Nước lẩu, hải sản, rau củ",
    instructions: "Nấu nước lẩu, cho nguyên liệu vào ăn nóng.",
  },
  {
    id: "MEAL020",
    name: "Cá hồi áp chảo",
    calories: 250,
    proteins: 22,
    fats: 15,
    carbs: 0,
    ingredients: "Cá hồi, bơ, tiêu, muối",
    instructions: "Áp chảo cá hồi với bơ, nêm muối và tiêu.",
  },
];